# Deploy Environment Bicep
on: [push]
paths:
  - 'deployEnvBicep.yml
name: Build and deploy Environment
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy bicep
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./node-python/environment.bicep
          parameters: 'environmentName=env-nodepython'
          failOnStdErr: false
