name: Trigger auto deployment for queuereader

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'orderapi/queuereaderapp/**'
    - '.github/workflows/queuereader-AutoDeployTrigger-3ff7470c-7e30-4408-ab30-90bd9123f4a4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrcasxftp.azurecr.io
          username: ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }}
          password: ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrcasxftp.azurecr.io/queuereader:${{ github.sha }}
          file: ./orderapi/queuereaderapp/Dockerfile
          context: ./orderapi/queuereaderapp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.QUEUEREADER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n queuereader -g rg-aca-casxftp --server acrcasxftp.azurecr.io --username  ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }} --password ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }}
            az containerapp update -n queuereader -g rg-aca-casxftp --image acrcasxftp.azurecr.io/queuereader:${{ github.sha }}
